import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from spectral import SpectralNorm
import numpy as np

class Self_Attn(nn.Module):
    """ Self attention Layer"""
    def __init__(self,in_dim,activation):
        super().__init__()
        
        # Initializing model param
        self.chanel_in = in_dim
        self.activation = activation
        
        # Construct the module
        self.query_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim//2 , kernel_size= 1)
        self.key_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim//2 , kernel_size= 1)
        self.value_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim , kernel_size= 1)
        
        self.gamma = nn.Parameter(torch.zeros(1))
        self.softmax  = nn.Softmax(dim=-1)
        
    def forward(self,x):
        """
            inputs :
                x : input feature maps( B * C * W * H)
            returns :
                out : self attention value + input feature 
                attention: B * N * N (N is Width*Height)
        """
        m_batchsize,C,width ,height = x.size()
        
        proj_query  = self.query_conv(x).view(m_batchsize, -1, width*height).permute(0,2,1) # B * N * C
        proj_key =  self.key_conv(x).view(m_batchsize, -1, width*height) # B * C * N
        energy =  torch.bmm(proj_query, proj_key) # batch matrix-matrix product
        
        attention = self.softmax(energy) # B * N * N
        proj_value = self.value_conv(x).view(m_batchsize, -1, width*height) # B * C * N
        out = torch.bmm(proj_value, attention.permute(0,2,1)) # batch matrix-matrix product
        out = out.view(m_batchsize,C,width,height) # B * C * W * H
        
        out = self.gamma*out + x
        return out, attention

class Generator(nn.Module):
    """
    Generator
    input: 
        z: latent matrix with shape of (batch_size, 100)
    output: 
        out: generated image with shape (batch_size, 1, imsize, imsize)
        p1, p2: attention matrix generated by attn layer
    """

    def __init__(self, batch_size, image_size=64, z_dim=100, conv_dim=64):
        super().__init__()
        self.imsize = image_size
        mult = 8
        
        layer1 = [
            SpectralNorm(nn.ConvTranspose2d(in_channels = z_dim, out_channels = conv_dim * mult, 4)),
            nn.BatchNorm2d(conv_dim * mult),
            nn.ReLU()
        ]
        curr_dim = conv_dim * mult
        
        layer2 = [
            SpectralNorm(nn.ConvTranspose2d(in_channels = curr_dim, out_channels = int(curr_dim / 2), 4, 2, 1)),
            nn.BatchNorm2d(int(curr_dim / 2)),
            nn.ReLU()
        ]
        curr_dim = int(curr_dim / 2)
        
        layer3 = [
            SpectralNorm(nn.ConvTranspose2d(in_channels = curr_dim, out_channels = int(curr_dim / 2), 4, 2, 1)),
            nn.BatchNorm2d(int(curr_dim / 2)),
            nn.ReLU()]
        curr_dim = int(curr_dim / 2)
        
        self.attn1 = Self_Attn(curr_dim, 'relu')
        
        layer4 = [
            SpectralNorm(nn.ConvTranspose2d(in_channels = curr_dim, out_channels = int(curr_dim / 2), 4, 2, 1)),
            nn.BatchNorm2d(int(curr_dim / 2)),
            nn.ReLU()]
        curr_dim = int(curr_dim / 2)
        
        self.attn2 = Self_Attn(curr_dim,  'relu')
        
        last = [
            nn.ConvTranspose2d(curr_dim, 3, 4, 2, 1),
            nn.Tanh()
        ]
        
        self.l1 = nn.Sequential(*layer1)
        self.l2 = nn.Sequential(*layer2)
        self.l3 = nn.Sequential(*layer3)
        self.l4 = nn.Sequential(*layer4)
        self.last = nn.Sequential(*last)

    def forward(self, z):
        z = z.view(z.size(0), z.size(1), 1, 1)
        out=self.l1(z)
        out=self.l2(out)
        out=self.l3(out)
        out,p1 = self.attn1(out)
        out=self.l4(out)
        out,p2 = self.attn2(out)
        out=self.last(out)

        return out, p1, p2


class Discriminator(nn.Module):
    """Discriminator, Auxiliary Classifier."""

    def __init__(self, batch_size=64, image_size=64, conv_dim=64):
        super(Discriminator, self).__init__()
        self.imsize = image_size
        layer1 = [
            SpectralNorm(nn.Conv2d(3, conv_dim, 4, 2, 1)),
            nn.LeakyReLU(0.1)
        ]
        curr_dim = conv_dim
        layer2 = [
            SpectralNorm(nn.Conv2d(curr_dim, curr_dim * 2, 4, 2, 1)), 
            nn.LeakyReLU(0.1)
        ]
        curr_dim = curr_dim * 2
        layer3 = [
            SpectralNorm(nn.Conv2d(curr_dim, curr_dim * 2, 4, 2, 1)), 
            nn.LeakyReLU(0.1)
        ]
        curr_dim = curr_dim * 2
        self.attn1 = Self_Attn(curr_dim, 'relu')
        layer4 = [
            SpectralNorm(nn.Conv2d(curr_dim, curr_dim * 2, 4, 2, 1)), 
            nn.LeakyReLU(0.1)
        ]
        curr_dim = curr_dim * 2
        self.attn2 = Self_Attn(curr_dim, 'relu')
        last = [
            nn.Conv2d(curr_dim, 1, 4)
        ]

        self.l1 = nn.Sequential(*layer1)
        self.l2 = nn.Sequential(*layer2)
        self.l3 = nn.Sequential(*layer3)
        self.l4 = nn.Sequential(*layer4)
        self.last = nn.Sequential(*last)

    def forward(self, x):
        out = self.l1(x)
        out = self.l2(out)
        out = self.l3(out)
        out,p1 = self.attn1(out)
        out=self.l4(out)
        out,p2 = self.attn2(out)
        out=self.last(out)

        return out.squeeze(), p1, p2
